---
# https://openwrt.org/docs/guide-user/services/nas/samba_configuration
# https://openwrt.org/docs/guide-user/services/nas/cifs.server

- name: Include variables for OpenWrt <= 18.06
  include_vars: 18.yml
  when:
  - ansible_distribution_major_version is defined
  - ansible_distribution_major_version|int <= 18

- name: Install {{ _samba_server_package }}
  opkg:
    name: "{{ _samba_server_package }}"

- name: Install {{ _luci_app_samba_package }}
  when: samba_luci
  opkg:
    name: "{{ _luci_app_samba_package }}"

- name: Find USB drive mount point
  shell: block info | grep /dev/sd | grep -v swap | grep -o -E 'MOUNT="[^"]+"' | cut -d\" -f2
  register: block_mount
  changed_when: no

- name: Configure Samba Share
  uci:
    command: section
    config: "{{ _samba_name }}"
    type: sambashare
    find_by:
      path: "{{ block_mount.stdout }}"
    value:
      name: "{{ block_mount.stdout | basename }}"
      path: "{{ block_mount.stdout }}"
      create_mask: "{{ samba_create_mask }}"
      dir_mask: "{{ samba_dir_mask }}"
      read_only: "{{ 'yes' if samba_read_only else 'no' }}"
      guest_ok: "{{ 'yes' if samba_guest_ok else 'no' }}"
      browserable: "{{ 'yes' if samba_browserable else 'no' }}"
      users: "{{ samba_users }}"
  notify:
  - uci commit
  - service samba restart
  when: block_mount.stdout != ""

- name: Install wsdd2
  when: samba_wsd
  opkg:
    name: wsdd2
